<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>vision_grasp_bringup</name>
  <version>0.1.0</version>
  <description>Vision grasp system main launch and parameter configuration package</description>
  <maintainer email="shijue2@example.com">shijue2</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>vision_grasp_camera</exec_depend>
  <exec_depend>vision_grasp_serial</exec_depend>
  <exec_depend>vision_grasp_lidar</exec_depend>
  <exec_depend>vision_grasp_state_machine</exec_depend>
  <exec_depend>interfaces</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

